/**
 * Permission-related data transfer objects (DTOs) and interfaces.
 *
 * This file defines the structure of permission-related data that is transferred between different layers of the application, such as the domain layer, application layer, and infrastructure layer. It includes the Permission interface, which represents a specific permission within the system.
 *
 * The purpose of these DTOs is to provide a consistent and standardized way of handling data transfer across different parts of the application, ensuring that the data being transferred adheres to the expected structure and format.
 */

import type { Permission } from '../permission/index.ts'
import type { UUID } from '../shared/uid.ts'
import type { PaginatedResult, PaginationInput, SortInput } from './common.dto.ts'

// =============================================================================
// INPUT DTOs
// =============================================================================

/**
 * Input for creating a new permission (uses Permission as a base, but excludes fields that are generated by the system or not required for creation).
 */

export type CreatePermissionInput = Omit<Permission, 'id' | 'createdAt' | 'updatedAt'>

/**
 * Input for updating an existing permission (uses Permission as a base, but excludes fields that are generated by the system or not required for updates).
 */

export type UpdatePermissionInput = Omit<Permission, 'createdAt' | 'updatedAt'>

export interface DeletePermissionInput {
  id: string
  deletedBy: UUID
}

export interface GetPermissionByIdInput {
  id: string
}

export interface ListPermissionsInput {
  filters: PermissionFilters
  pagination: PaginationInput
  sort?: SortInput<PermissionSortField>
}

export interface PermissionFilters {
  domain?: string
}

export type PermissionSortField = 'name' | 'domain' | 'createdAt' | 'updatedAt'

// =============================================================================
// OUTPUT DTOs
// =============================================================================

export type PermissionDTO = Permission

export type PermissionListDTO = PaginatedResult<PermissionDTO>

export interface TotalPermissionsDTO {
  totalPermissions: number
}

export interface PermissionPositionDistributionDTO extends TotalPermissionsDTO {
  items: {
    permissionId: UUID
    permissionName: string
    positionCount: number
  }[]
}
