/**
 * Position-related data transfer objects (DTOs) and interfaces.
 *
 * This file defines the structure of position-related data that is transferred between different layers of the application, such as the domain layer, application layer, and infrastructure layer. It includes the Position interface, which represents a position's role or position within the organization.
 *
 * The purpose of these DTOs is to provide a consistent and standardized way of handling data transfer across different parts of the application, ensuring that the data being transferred adheres to the expected structure and format.
 */

import type { UUID } from '../shared/uid.ts'
import type { Position } from '../user/index.ts'
import type { PaginatedResult, PaginationInput, SortInput } from './common.dto.ts'

// =============================================================================
// INPUT DTOs
// =============================================================================

/**
 * Input for creating a new position (uses Position as a base, but excludes fields that are generated by the system or not required for creation).
 */

export type CreatePositionInput = Omit<Position, 'id' | 'createdAt' | 'updatedAt'>

/**
 * Input for updating an existing position (uses Position as a base, but excludes fields that are generated by the system or not required for updates).
 */

export type UpdatePositionInput = Omit<Position, 'id' | 'createdAt' | 'updatedAt'>

export interface DeletePositionInput {
  id: string
  deletedBy: UUID
}

export interface GetPositionByIdInput {
  id: string
}

export interface GetPositionByEmailInput {
  email: string
}

export interface ListPositionsInput {
  filters: PositionFilters
  pagination: PaginationInput
  sort?: SortInput<PositionSortField>
}

export interface PositionFilters {
  permissions?: string[]
}

export type PositionSortField = 'name' | 'createdAt' | 'updatedAt'

// =============================================================================
// OUTPUT DTOs
// =============================================================================

export type PositionDTO = Position

export type PositionListDTO = PaginatedResult<PositionDTO>

export type TotalPositionsDTO = {
  totalPositions: number
}
