/**
 * User-related data transfer objects (DTOs) and interfaces.
 *
 * This file defines the structure of user-related data that is transferred between different layers of the application, such as the domain layer, application layer, and infrastructure layer. It includes the UserProfile interface, which represents the essential information about a user, and the Position interface, which represents a user's role or position within the organization.
 *
 * The purpose of these DTOs is to provide a consistent and standardized way of handling data transfer across different parts of the application, ensuring that the data being transferred adheres to the expected structure and format.
 */

import type { UUID } from '../shared/uid.ts'
import type { UserProfile } from '../user/index.ts'
import type { PaginatedResult, PaginationInput, SortInput } from './common.dto.ts'

// =============================================================================
// INPUT DTOs
// =============================================================================

/**
 * Input for creating a new user (uses UserProfile as a base, but excludes fields that are generated by the system or not required for creation).
 */

export type CreateUserInput = Omit<
  UserProfile,
  'emailVerified' | 'disabled' | 'createdAt' | 'updatedAt'
>

/**
 * Input for updating an existing user (uses UserProfile as a base, but excludes fields that are generated by the system or not required for updates).
 */

export type UpdateUserInput = Omit<
  UserProfile,
  'emailVerified' | 'disabled' | 'createdAt' | 'updatedAt'
>

export interface DeleteUserInput {
  id: string
  deletedBy: UUID
}

export interface GetUserByIdInput {
  id: string
}

export interface GetUserByEmailInput {
  email: string
}

export interface ListUsersInput {
  filters: UserFilters
  pagination: PaginationInput
  sort?: SortInput<UserSortField>
}

export interface UserFilters {
  positionIds?: UUID[]
  disabled?: boolean
  emailVerified?: boolean
}

export type UserSortField = 'firstName' | 'lastName' | 'email' | 'createdAt' | 'updatedAt'

// =============================================================================
// OUTPUT DTOs
// =============================================================================

export type UserDTO = Omit<UserProfile, 'password'>

export type UserListDTO = PaginatedResult<UserDTO>

export interface TotalUsersDTO {
  totalUsers: number
}

export interface PositionDistributionDTO extends TotalUsersDTO {
  items: {
    positionId: UUID
    positionName: string
    userCount: number
  }[]
}
