import './globals.css'

import type { Metadata } from 'next'
import { Roboto, Roboto_Condensed } from 'next/font/google'
import { Toaster } from 'sonner'

import CoreProvider from '@/components/providers/CoreProvider'
import { cn } from '@/lib/utils'

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
})

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-roboto-condensed',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cn('font-sans', roboto.variable, robotoCondensed.variable)}>
      <body className="antialiased">
        <CoreProvider>{children}</CoreProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  )
}
