import type { Metadata } from 'next'

import { AppNavigation } from '@/components/shared'
import { SidebarProvider } from '@/components/ui/sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function UsersLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <SidebarProvider>
      <main className="flex w-full min-w-0 flex-col md:flex-row">
        <AppNavigation />
        <div className="w-full pl-4">{children}</div>
      </main>
    </SidebarProvider>
  )
}
